### ISSUE TITLE
How run Job in others host target and include in report

### ISSUE THREAD

**Issue by eduardoc25** [jwkenney/ansible-job-report#1]
Example:

- name: PLAY 2 Run jobs and generate report
  hosts: winhost
  gather_facts: no
  order: sorted
...
- name: PLAY 3 Run jobs and include in report
  hosts: linuxhost
  gather_facts: no
  order: sorted
...
- name: PLAY 4 Run jobs and include in report
  hosts: machost
  gather_facts: no
  order: sorted
...

**Comment by jwkenney** [comment]
The playbook was designed to compile all results within the scope of a single play.

To add support for different types of OS, the most straightforward approach would be to create additional task files named after the OS or Distribution, as shown by the `ansible_system` fact (for OS) or `ansible_distribution` fact (for Distro). Names will be case-sensitive. Below we put them in a `tasks/` subfolder next to the playbook.

```
ansible-job-report/
├── demo.gif
├── job_report.yaml
├── reports
│   └── job_report_example.html
├── tasks
│   ├── Linux.yml
│   └── Windows.yml
└── templates
    ├── job_report_host.j2
    ├── job_report_master.j2
    └── stylesheet.css.j2
```

In the `job_report.yaml` playbook, `tasks:` section, you would call the `include_tasks` module to pull in your task files per OS or distro.

```
    - name: Invoke per-OS task file
      include_tasks: "tasks/{{ ansible_system }}.yml"
```

In the per-OS task files, be sure to register the same variable names where appropriate, and/or add conditionals in your report template to only print output for the appropriate OS/Distro.

**Comment by eduardoc25** [comment]
Thanks for the information... very good template!

Cheers
